# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14fc1b4066805b3f5fac1557238af9b17a4cf0ac1bfa63ecac193c540cf4505083ee91c43705957e5b48ae6d469df902e851b27580a5f74a8db9d67ef5cb4ee8

test:
  secret_key_base: 8338362fc4e2db8ec63c08539db495ae2539c062d4c0cd8ba7579a31598063b2acd1068ba2af6d0c51a604fc61a18705844172734cc733d7b8a35d05abf4aa6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
